"""add notification_trigger_log table

Revision ID: 4235f84e5eca
Revises: 03fd0b86f724
Create Date: 2025-06-21 04:05:16.618270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4235f84e5eca'
down_revision = '03fd0b86f724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_trigger_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('target_event_date', sa.Date(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('job_run_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.lease_id'], name=op.f('fk_notification_trigger_logs_lease_id_leases')),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.notification_id'], name=op.f('fk_notification_trigger_logs_notification_id_notifications')),
    sa.ForeignKeyConstraint(['rule_id'], ['landlord_reminder_rules.rule_id'], name=op.f('fk_notification_trigger_logs_rule_id_landlord_reminder_rules')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_notification_trigger_logs')),
    sa.UniqueConstraint('notification_id', name=op.f('uq_notification_trigger_logs_notification_id')),
    sa.UniqueConstraint('rule_id', 'lease_id', 'target_event_date', name='_rule_lease_event_uc')
    )
    op.create_index(op.f('ix_notification_trigger_logs_job_run_id'), 'notification_trigger_logs', ['job_run_id'], unique=False)
    op.create_index(op.f('ix_notification_trigger_logs_lease_id'), 'notification_trigger_logs', ['lease_id'], unique=False)
    op.create_index(op.f('ix_notification_trigger_logs_notification_id'), 'notification_trigger_logs', ['notification_id'], unique=True)
    op.create_index(op.f('ix_notification_trigger_logs_rule_id'), 'notification_trigger_logs', ['rule_id'], unique=False)
    op.create_index(op.f('ix_notification_trigger_logs_target_event_date'), 'notification_trigger_logs', ['target_event_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_trigger_logs_target_event_date'), table_name='notification_trigger_logs')
    op.drop_index(op.f('ix_notification_trigger_logs_rule_id'), table_name='notification_trigger_logs')
    op.drop_index(op.f('ix_notification_trigger_logs_notification_id'), table_name='notification_trigger_logs')
    op.drop_index(op.f('ix_notification_trigger_logs_lease_id'), table_name='notification_trigger_logs')
    op.drop_index(op.f('ix_notification_trigger_logs_job_run_id'), table_name='notification_trigger_logs')
    op.drop_table('notification_trigger_logs')
    # ### end Alembic commands ###
