"""add landlord mpesa and gateway config models

Revision ID: 9563c90ba323
Revises: dc8c45dcfe20
Create Date: 2025-06-21 03:38:50.120106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9563c90ba323'
down_revision = 'dc8c45dcfe20'
branch_labels = None
depends_on = None

# Define SA Enums based on models.enums
mpesa_shortcode_type_enum = sa.Enum('PAYBILL', 'TILL_NUMBER', 'NONE', name='mpesashortcodetype')
gateway_environment_enum = sa.Enum('SANDBOX', 'PRODUCTION', 'TESTING', name='gatewayenvironment')
# GatewayType is already centralized in models.enums and theoretically its previous migration (7820b5bbc25f)
# created a DB-level enum 'gatewaytype'. We will refer to that existing name if using native PG enums,
# or define it here if we need to ensure its values for SQLite CHECK constraints.
# For consistency with how other enums are handled in migrations when used by new tables:
gateway_type_enum = sa.Enum(
    'PESAPAL', 'STRIPE', 'FLUTTERWAVE', 'PAYPAL', 'MPESA_STK_PUSH',
    'OTHER_GENERIC_GATEWAY', 'MANUAL_BANK_TRANSFER_VERIFICATION',
    name='gatewaytype' # Ensure this name matches the one used in 7820b5bbc25f if DB enums are used
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landlord_mpesa_configs',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('shortcode_type', mpesa_shortcode_type_enum, nullable=False),
    sa.Column('paybill_number', sa.String(length=20), nullable=True),
    sa.Column('till_number', sa.String(length=20), nullable=True),
    sa.Column('consumer_key_encrypted', sa.String(length=512), nullable=True),
    sa.Column('consumer_secret_encrypted', sa.String(length=512), nullable=True),
    sa.Column('passkey_encrypted', sa.String(length=512), nullable=True),
    sa.Column('account_reference_prefix', sa.String(length=50), nullable=True),
    sa.Column('callback_url_override', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_validation_check_at', sa.DateTime(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=True),
    sa.Column('validation_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.user_id'], name=op.f('fk_landlord_mpesa_configs_landlord_id_users')),
    sa.PrimaryKeyConstraint('config_id', name=op.f('pk_landlord_mpesa_configs'))
    )
    op.create_index(op.f('ix_landlord_mpesa_configs_is_active'), 'landlord_mpesa_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_landlord_mpesa_configs_landlord_id'), 'landlord_mpesa_configs', ['landlord_id'], unique=True)
    op.create_index(op.f('ix_landlord_mpesa_configs_paybill_number'), 'landlord_mpesa_configs', ['paybill_number'], unique=False)
    op.create_index(op.f('ix_landlord_mpesa_configs_till_number'), 'landlord_mpesa_configs', ['till_number'], unique=False)

    op.create_table('landlord_gateway_configs',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('gateway_type', gateway_type_enum, nullable=False),
    sa.Column('account_identifier', sa.String(length=255), nullable=True),
    sa.Column('credential_1_encrypted', sa.String(length=512), nullable=True),
    sa.Column('credential_2_encrypted', sa.String(length=512), nullable=True),
    sa.Column('credential_3_encrypted', sa.String(length=512), nullable=True),
    sa.Column('additional_settings_encrypted', sa.JSON(), nullable=True),
    sa.Column('environment', gateway_environment_enum, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_validation_check_at', sa.DateTime(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=True),
    sa.Column('validation_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.user_id'], name=op.f('fk_landlord_gateway_configs_landlord_id_users')),
    sa.PrimaryKeyConstraint('config_id', name=op.f('pk_landlord_gateway_configs')),
    sa.UniqueConstraint('landlord_id', 'gateway_type', name=op.f('uq_landlord_gateway_configs_landlord_id_gateway_type'))
    )
    op.create_index(op.f('ix_landlord_gateway_configs_gateway_type'), 'landlord_gateway_configs', ['gateway_type'], unique=False)
    op.create_index(op.f('ix_landlord_gateway_configs_is_active'), 'landlord_gateway_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_landlord_gateway_configs_landlord_id'), 'landlord_gateway_configs', ['landlord_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_landlord_gateway_configs_landlord_id'), table_name='landlord_gateway_configs')
    op.drop_index(op.f('ix_landlord_gateway_configs_is_active'), table_name='landlord_gateway_configs')
    op.drop_index(op.f('ix_landlord_gateway_configs_gateway_type'), table_name='landlord_gateway_configs')
    op.drop_table('landlord_gateway_configs')

    op.drop_index(op.f('ix_landlord_mpesa_configs_till_number'), table_name='landlord_mpesa_configs')
    op.drop_index(op.f('ix_landlord_mpesa_configs_paybill_number'), table_name='landlord_mpesa_configs')
    op.drop_index(op.f('ix_landlord_mpesa_configs_landlord_id'), table_name='landlord_mpesa_configs')
    op.drop_index(op.f('ix_landlord_mpesa_configs_is_active'), table_name='landlord_mpesa_configs')
    op.drop_table('landlord_mpesa_configs')

    # Drop Enums (PostgreSQL specific, adjust for other DBs)
    # Commenting out for SQLite compatibility.
    # Only drop enums created in *this* migration if they aren't shared or already dropped by other migrations.
    # mpesa_shortcode_type_enum.drop(op.get_bind(), checkfirst=False)
    # gateway_environment_enum.drop(op.get_bind(), checkfirst=False)
    # gateway_type_enum is potentially shared and created by migration 7820b5bbc25f.
    # Avoid dropping it here if it's expected to persist for other tables (like gateway_transactions).
    # If this migration were the *only* user, or if its name was unique, then dropping would be fine.
    # For safety, if an enum is shared, it's typically created in its own migration or the first migration that uses it,
    # and dropped only when no longer needed by any table.
    # Given that 'gatewaytype' was created by 7820b5bbc25f, we should not drop it here.
    # ### end Alembic commands ###
